### ISSUE TITLE
Preprocessor: support run for the default SAVE-developed test suites 

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#102]
We need to run our **OWN** test suites. In this case the developer of static analyzer need to provide us his BINARY and how to run it (configuration/save.properties) or a string for save execution.

**Comment by petertrr** [comment]
- different endpoint similar to `/submitExecutionRequest`
- additional logic in preprocessor to store provided files in the same folder as cloned repo (part of SAVE repo? or some sort of SAVE-suites?)
- support this on frontend, probably as part of #56
