### ISSUE TITLE
Save cloud architectural diagram 

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#103]
We need:
1) to add our diagram to the readme
2) add NUMBERs of steps to the diagram
3) polish diagram with swimlane diagram

**Comment by petertrr** [comment]
@kentr0w what is the status of this? I believe we already have these diagrams, can we upload them into the repo or on wiki?

**Comment by petertrr** [comment]
I assume, it's closed in https://github.com/cqfn/save-cloud/commit/f90a2153ca4d127ce6853283fdb25a81af7c9257

**Comment by akuleshov7** [comment]
I added common diagram to our readme, I guess we need to add also swimlane

@kentr0w please:
1) update our arch diagram with number of steps
2) please attach SVG (!) swimlane to our readme or wiki

**Comment by kentr0w** [comment]
[Diagram](https://github.com/cqfn/save-cloud#architecture-and-design)

**Comment by petertrr** [comment]
Do we have swimlane anywhere?

**Comment by kentr0w** [comment]
Yes, I sent it to @akuleshov7.
