### ISSUE TITLE
Create endpoint to get all default test suite names

### ISSUE THREAD

**Issue by kentr0w** [cqfn/save-cloud#137]
This task should cover both backend and the forntend. 
We need also to create a good name for this endpoint.

On frontend we should propely update these buttons:
![image](https://user-images.githubusercontent.com/58667063/125059388-f179ef00-e0b3-11eb-82e4-27c1cea4ddce.png)

**Comment by petertrr** [comment]
Originally discussed in: https://github.com/cqfn/save-cloud/pull/131#discussion_r647530605
