### ISSUE TITLE
Set execution status based on results

### ISSUE THREAD

**Issue by petertrr** [cqfn/save-cloud#157]
E.g., if all agents have crashed, set status FAIL or something.

We should keep in mind, that with current implementation if agent has finished with status non-FINISHED, then it is overriden by IDLE after WaitResponse and we lose this data upon shutdown. But it could be handled and used to set execution status. Of course, we could retrieve this data from database by filtering by agent id and analyzing states, if needed.

Requirements:
* [x] #143
* [x] #179

**Comment by akuleshov7** [comment]
@petertrr can we give this task to @kgevorkyan so he will be able to study Spring? ...

**Comment by petertrr** [comment]
> @petertrr can we give this task to @kgevorkyan so he will be able to study Spring? ...

This task is actually not very much about Spring, and should be implemented only after we integrate JSON reporter in #134. I think something like #137 is more beginner-friendly and spring-oriented

**Comment by petertrr** [comment]
Since this issue was created, we have added a count of passed/failed test and are displaying it in the same table with history. Now it's logical, because execution status indicates whether execution has failed with or without internal errors, and when user is intereseted in details, they can click the line of interest. The only thing related to this issue - we need to mark failed and passed executions with symbol and color.
