### ISSUE TITLE
Preprocessor should have a mechanism of how to add our own default test suites 

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#170]
This is a continuation of https://github.com/cqfn/save-cloud/issues/102

We should extend the logic of the preprocessor, so we will have the mechanism of easy **UPLOADING** of our own default test suites.
For example:
1) we need some endpoint/configuration file that will contain links to the repositories with SAVE suites.
2) preprocessor should download, parse, update a database and the list of default test suites 
3) put these default save test suites to some directory on server so it will always be prepared in case of loading it from the frontend
~4) please also create some endpoint that we will be able to use to manually trigger the update these tests (later we can add cron tasks)~ moved to #198

**Comment by akuleshov7** [comment]
This should also be linked with Frontend https://github.com/cqfn/save-cloud/issues/137

**Comment by petertrr** [comment]
I think we can use Quartz with JdbcStore to schedule repository updates, but it can be implemented in a separate task
