### ISSUE TITLE
Database: create schema for tests and agents

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#19]
Create and support schema for tests and agent status in save-common. Schema should use JPA-API. 

Schema for tests should cover test run status.
Schema for agents should cover agent status.

**Comment by petertrr** [comment]
As noted on [wiki](https://github.com/cqfn/save-cloud/wiki/SAVE-components-&-plan-of-work), test result status are `[PASSED, FAILED, IGNORED, INTERNAL_ERROR (CLI exit 1), TEST_ERROR (CLI exit 42)]`; AgentStates as already is in save-common, and additionally add CLI_FAILED, BACKEND_FAILURE, BACKEND_UNREACHABLE instad of ERROR
