### ISSUE TITLE
Database: support MySQL client

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#20]
Support logic for the communication with MySQL database for save-backend and save-orchestrator.
This task also reflects the liquibase support.

**Comment by akuleshov7** [comment]
If we are using Hibernate - may be we can just create proper schemas and that's all

**Comment by petertrr** [comment]
> If we are using Hibernate - may be we can just create proper schemas and that's all

I believe this task should also include proper `prod` spring profile and supporting liquibase.

**Comment by petertrr** [comment]
We should also think about local deployment of services, including database. There are several options:
* Use spring-liquibase integration and add a testcontainers entity to dev profile
* Add mysql DB to docker-compose for local deployment. This option will make liquibase deployment consistent for dev and prod.
