### ISSUE TITLE
Create empty `TestExecution`s in `DownloadProjectController#prepareExecutionForStandard`

### ISSUE THREAD

**Issue by kgevorkyan** [cqfn/save-cloud#221]
In `DownloadProjectController.kt`, `prepareExecutionForStandard()` we should not save test suites to the DB, as we already have them.

We should just initialize tests, like it specified in corresponding `FixMe`

**Comment by petertrr** [comment]
> initialize tests

test executions

**Comment by kgevorkyan** [comment]
We should just create empty executions
