### ISSUE TITLE
Backend: support controllers for database related work

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save-cloud#37]
We (with @petertrr) decided that we should have a single point to work with a database for all microservices.
For example: `orchestrator`, `backend-preprocessor` and `backend` should work with the same microservice that will do the same base-related work. 

So we need 2 endpoints for it:
1. Orchestrator (to receive post requests with Statuses)
2. Backend-preprocessor (to receive post requests with test IDs)

**Comment by petertrr** [comment]
Endpoint for test results is covered in #21
